---
AWSTemplateFormatVersion: "2010-09-09"
Description: Foundational Organization Security (SH) Resource Deployment

Metadata:
  TemplateInfo:
    Name: stackset-sh-organization-foundation
    Description: Foundational Organization Security Resource Deployment
    Version: 1.0.0
    Source: armory/organization/cfn/stackset-sh-organization-foundation.yaml
    Note: Deploy from management account to all accounts for Security Hub Checks
    LastUpdated: 20241206
    Nonce: 20241206

Parameters:
  SupportAccountId:
    Description: Account ID for support account assume role
    Type: String

  DeploymentOUs:
    Description: Which ORG OU(s) is this deploying to
    Type: String
    MinLength: 6

  HomeRegion:
    Description: Home Control Tower and Central Security Hub Region
    Type: String
    MinLength: 8

  NonceValue:
    Description: Random Identifier to force update of stackset resource
    Type: String

Conditions:
  cIsHomeRegion: !Equals [!Ref AWS::Region, !Ref HomeRegion] ## only launch global resources in single/home region

Resources:
  ##############################
  ## IAM Support Role (IAM.18 - Low)
  ##############################

  SupportRoleMgmt:
    Condition: cIsHomeRegion
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/armory.sentri.cloud/iam/cfn/role-support-assume.yaml
      Parameters:
        SupportAccountId: !Ref SupportAccountId
        HomeRegion: !Ref HomeRegion
        NonceValue: !Ref NonceValue

  SupportRoleChildren:
    Condition: cIsHomeRegion
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: sh-organization-foundation
      Description: Support Role - DO NOT DELETE - Child Account Support Access Role
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_AUTO_EXPAND
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 100
        RegionConcurrencyType: PARALLEL
      StackInstancesGroup:
        - Regions:
            - !Ref HomeRegion
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref DeploymentOUs
      Parameters:
        - ParameterKey: SupportAccountId
          ParameterValue: !Ref SupportAccountId
        - ParameterKey: HomeRegion
          ParameterValue: !Ref HomeRegion
        - ParameterKey: NonceValue
          ParameterValue: !Ref NonceValue
      TemplateURL: https://s3.us-east-2.amazonaws.com/armory.sentri.cloud/iam/cfn/role-support-assume.yaml

  ##############################
  ## PASSWORD LAMBDA (IAM.15- Med, IAM.16 - Low, IAM.22 - Med)
  ##############################

  PasswordSettingsMgmt:
    Condition: cIsHomeRegion
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/armory.sentri.cloud/iam/cfn/iam-settings-password-policy.yaml
      Parameters:
        HomeRegion: !Ref HomeRegion
        NonceValue: !Ref NonceValue

  PasswordSettingsChildren:
    Condition: cIsHomeRegion
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: iam-settings-password-policy
      Description: IAM Settings - DO NOT DELETE - IAM User Password Default Policy
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_AUTO_EXPAND
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 100
        RegionConcurrencyType: PARALLEL
      StackInstancesGroup:
        - Regions:
            - !Ref HomeRegion
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref DeploymentOUs
      Parameters:
        - ParameterKey: HomeRegion
          ParameterValue: !Ref HomeRegion
        - ParameterKey: NonceValue
          ParameterValue: !Ref NonceValue
      TemplateURL: https://s3.us-east-2.amazonaws.com/armory.sentri.cloud/iam/cfn/iam-settings-password-policy.yaml
