AWSTemplateFormatVersion: 2010-09-09
Description: OIDC IDP for GitHub Actions

Metadata:
  TemplateInfo:
    Name: idp-github-oidc
    Description: IAM IDP for GitHub Actions OIDC
    Deploy-To: Once in any account
    Version: 1.0.0
    Source: armory/iam/cfn/github/idp-github-oidc.yaml
    Note: This template is part of the SC Consulting product deployment
    QuickStackLink: Not deployed to bucket currently
    LastUpdated: 20241206
    Nonce: 20241206

Parameters:
  UpdateNonce:
    Description: >
      Optional: Random Output Identifier to force update of resource (Used for deployment CI/CD and StackSet updates)
    Type: String

Resources:
  IDP:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Url: https://token.actions.githubusercontent.com
      Tags:
        - Key: Name
          Value: GitHubActions

Outputs:
  UpdateNonce:
    Description: A Random Output Identifier to force update of resource (Used for deployment CI/CD and StackSet updates)
    Value: !Ref UpdateNonce
  IdpARN:
    Description: ARN of Github OIDC Provider
    Value: !GetAtt IDP.Arn
    Export:
      Name: GitHubOidcIdpARN
