---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket for exteranlly accessible assets

Metadata:
  TemplateInfo:
    Name: bucket-external-assets
    Description: S3 Bucket for exteranlly accessible assets
    Version: 1.0.0
    Source: armory/s3/bucket-external-assets.yml
    Note: Deploy only to single region to prevent resource collision. (Recommended us-east-1)
    LastUpdated: 20241206
    Nonce: 20241206

Parameters:
  pBucketName:
    Description: Name of Bucket
    Type: String
    Default: assets.example.com

Resources:
  rAccessLogsBucket:
    Type: AWS::S3::Bucket
    # checkov:skip=CKV_AWS_18: Access Logs - Will not collect access logs on access logs
    # checkov:skip=CKV_AWS_21: Logging Bucket - No Versioning Required
    Properties:
      BucketName: !Sub ${pBucketName}-access-logs
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  rBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref pBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref rAccessLogsBucket
        LogFilePrefix: access-logs/

  rBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref rBucket
      PolicyDocument:
        Id: AwsCfnOrgTrust
        Version: 2012-10-17
        Statement:
          - Sid: PublicGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${pBucketName}/*
              - !Sub arn:${AWS::Partition}:s3:::${pBucketName}

Outputs:
  oBucketURL:
    Value: !Sub https://${rBucket.DomainName}
    Description: Endpoint URL for Asset Bucket
