---
AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation Stackset Admin and Execution Roles

Metadata:
  TemplateInfo:
    Name: stackset-iam-cloudformation-roles
    Description: CloudFormation Stackset Admin and Execution Roles
    Version: 1.0.0
    Source: armory/iam/stackset-cloudformation-roles.yaml
    Note: Deploy required roles with trusts for self-managed StackSets
    LastUpdated: 20241206
    Nonce: 20241206

Parameters:
  AdministratorAccountId:
    Description: Account ID for support account assume role
    Type: String

  DeploymentOUs:
    Description: Which ORG OU(s) is this deploying to
    Type: String
    MinLength: 6

  HomeRegion:
    Description: Home Control Tower and Central Security Hub Region
    Type: String
    MinLength: 8

  NonceValue:
    Description: Random Identifier to force update of stackset resource
    Type: String

Conditions:
  cIsHomeRegion: !Equals [!Ref AWS::Region, !Ref HomeRegion] ## only launch global resources in single/home region

Resources:
  CloudFormationAdminRole:
    Condition: cIsHomeRegion
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/armory.sentri.cloud/iam/role-cloudformation-admin.yaml
      Parameters:
        NonceValue: !Ref NonceValue

  CloudFormationExcutionRole:
    Condition: cIsHomeRegion
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: iam-role-assume-support
      Description: Support Role - DO NOT DELETE - Child Account Support Access Role
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_AUTO_EXPAND
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 100
        RegionConcurrencyType: PARALLEL
      StackInstancesGroup:
        - Regions:
            - !Ref HomeRegion
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref DeploymentOUs
      Parameters:
        - ParameterKey: AdministratorAccountId
          ParameterValue: !Ref AdministratorAccountId
        - ParameterKey: HomeRegion
          ParameterValue: !Ref HomeRegion
        - ParameterKey: NonceValue
          ParameterValue: !Ref NonceValue
      TemplateURL: https://s3.us-east-2.amazonaws.com/armory.sentri.cloud/iam/role-cloudformation-execution.yaml

  ##############################
  ## PASSWORD LAMBDA (IAM.15- Med, IAM.16 - Low)
  ##############################

  PasswordSettingsMgmt:
    Condition: cIsHomeRegion
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/armory.sentri.cloud/iam/iam-settings-password-policy.yaml
      Parameters:
        HomeRegion: !Ref HomeRegion
        NonceValue: !Ref NonceValue

  PasswordSettingsChildren:
    Condition: cIsHomeRegion
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: iam-settings-password-policy
      Description: IAM Settings - DO NOT DELETE - IAM User Password Default Policy
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_AUTO_EXPAND
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 100
        RegionConcurrencyType: PARALLEL
      StackInstancesGroup:
        - Regions:
            - !Ref HomeRegion
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref DeploymentOUs
      Parameters:
        - ParameterKey: HomeRegion
          ParameterValue: !Ref HomeRegion
        - ParameterKey: NonceValue
          ParameterValue: !Ref NonceValue
      TemplateURL: https://s3.us-east-2.amazonaws.com/armory.sentri.cloud/iam/iam-settings-password-policy.yaml

  ##############################
  ## EBS Encryption (EC2.7)
  ##############################

  EbsEncryptionMgmt:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-2.amazonaws.com/armory.sentri.cloud/ec2/ebs-enable-encryption.yaml
      Parameters:
        NonceValue: !Ref NonceValue

  EbsEncryptionChildren:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: enable-ebs-encryption
      Description: EBS Encryption - DO NOT DELETE - Configured Default EBS Encryption
      PermissionModel: SERVICE_MANAGED
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      Capabilities:
        - CAPABILITY_IAM
        - CAPABILITY_NAMED_IAM
        - CAPABILITY_AUTO_EXPAND
      OperationPreferences:
        MaxConcurrentPercentage: 100
        FailureTolerancePercentage: 100
        RegionConcurrencyType: PARALLEL
      StackInstancesGroup:
        - Regions: !Split [",", !Ref ConfigRegions]
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref DeploymentOUs
      Parameters:
        - ParameterKey: NonceValue
          ParameterValue: !Ref NonceValue
      TemplateURL: https://s3.us-east-2.amazonaws.com/armory.sentri.cloud/ec2/ebs-enable-encryption.yaml

Outputs:
  NonceValue:
    Description: Just an output of the Nonce value
    Value: !Ref NonceValue
