---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 Bucket for CUR Data Export

Metadata:
  TemplateInfo:
    Name: bucket-cur-data
    Description: S3 Bucket for collection of CUR Data Export
    Version: 1.0.0
    Source: armory/billing/cfn/bucket-cur-data.yaml
    Note: Recommended to deploy only to us-east-1 region to due to billing service endpoint.
    LastUpdated: 20241206
    Nonce: 20241206

Conditions:
  IsUsEast1: !Equals
    - !Ref AWS::Region
    - us-east-1

Resources:
  BillingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Condition: IsUsEast1
    Properties:
      BucketName: !Sub "legacy-cur-billing-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        LogFilePrefix: access-logs

  BillingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Condition: IsUsEast1
    Properties:
      Bucket: !Ref BillingBucket
      PolicyDocument:
        Statement:
        - Sid: EnableAWSDataExportsToWriteToS3AndCheckPolicy
          Effect: Allow
          Principal:
            Service:
            - billingreports.amazonaws.com
            - bcm-data-exports.amazonaws.com
          Action:
          - s3:PutObject
          - s3:GetBucketPolicy
          Resource:
          - !Sub ${BillingBucket.Arn}
          - !Sub ${BillingBucket.Arn}/*
          Condition:
            StringLike:
              aws:SourceArn:
              - arn:aws:cur:us-east-1:664418964237:definition/*
              - arn:aws:bcm-data-exports:us-east-1:664418964237:export/*
              aws:SourceAccount: !Sub ${AWS::AccountId}
