## Deploy manually in primary region prior to using for automation on any other project
AWSTemplateFormatVersion: 2010-09-09
Description: OIDC provider and initial role for GitHub Actions

Parameters:
  RoleName:
    Description: Name of the role
    Type: String
    Default: actions-primary

  Thumbprint:
    Description: Required by CFN. Now managed by AWS
    Type: CommaDelimitedList
    Default: 6938fd4d98bab03faadb97b34396831e3780aea1

  Audience:
    Description: List of allowed audience for the tokens
    Type: CommaDelimitedList
    Default: sts.amazonaws.com

  Repos:
    Description: Lost of Repos/Orgs and/or Git Refs to allow access for
    Type: CommaDelimitedList
    Default: repo:sAWeetStacks/*

  RolePath:
    Description: IAM Path required for the role (must end with `/`)
    Type: String
    Default: /github/

  ManagedPolicies:
    Description: List for arns for managed policies to attach to the role
    Type: CommaDelimitedList
    Default: arn:aws:iam::aws:policy/AdministratorAccess

Resources:
  IDP:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList: !Ref Audience
      ThumbprintList: !Ref Thumbprint
      Url: https://token.actions.githubusercontent.com
      Tags:
        - Key: Name
          Value: GitHubActions

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      Description: Primary Role for use in GitHub Actions
      Path: !Ref RolePath
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PrimaryGitHubActionsRole
            Effect: Allow
            Principal:
              Federated: !GetAtt IDP.Arn
            Action:
              - sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: !Ref Audience
              StringLike:
                token.actions.githubusercontent.com:sub: !Ref Repos
      ManagedPolicyArns: !Ref ManagedPolicies

Outputs:
  IdpARN:
    Description: ARN of Github OIDC Provider
    Value: !GetAtt IDP.Arn
    Export:
      Name: GitHubActionsIdpARN

  RoleARN:
    Description: ARN of GitHub Actions Role
    Value: !GetAtt Role.Arn
    Export:
      Name: GitHubActionsRoleARN
